# Generated by Django 5.1.4 on 2025-04-04 14:15

import django.core.validators
import labexam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=50)),
                ('student_last_name', models.CharField(max_length=50)),
                ('lab_name', models.CharField(choices=[('CC-I', 'CC-I'), ('CC-II', 'CC-II'), ('PL-I', 'PL-I'), ('DATABASE', 'DATABASE'), ('PL-II', 'PL-II'), ('PROJECT-I ', 'PROJECT-I'), ('DSP', 'DSP'), ('CN', 'CN'), ('SE', 'SE'), ('APL', 'APL'), ('LANGUAGE', 'LANGUAGE'), ('SP', 'SP'), ('ACN', 'ACN'), ('PROJECT-II', 'PROJECT-II'), ('SS', 'SS'), ('CAD', 'CAD'), ('AIML', 'AIML')], max_length=50)),
                ('program', models.CharField(choices=[('BTech', 'BTech'), ('MBATech', 'MBATech')], max_length=50)),
                ('branch', models.CharField(choices=[('CS', 'CS'), ('CE', 'CE'), ('IT', 'IT'), ('AIML', 'AIML')], max_length=50)),
                ('sap_id', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='SAP ID must be an 11-digit number.', regex='^\\d{11}$')])),
                ('roll_number', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Roll number must be like A123', regex='^[A-Za-z]\\d{3}$')])),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('file1_upload', models.FileField(upload_to=labexam.models.labexam_upload_path)),
                ('file2_upload', models.FileField(blank=True, null=True, upload_to=labexam.models.labexam_upload_path)),
                ('file3_upload', models.FileField(blank=True, null=True, upload_to=labexam.models.labexam_upload_path)),
                ('file4_upload', models.FileField(blank=True, null=True, upload_to=labexam.models.labexam_upload_path)),
                ('file5_upload', models.FileField(blank=True, null=True, upload_to=labexam.models.labexam_upload_path)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sap_id', 'date'), name='unique_sap_id_date')],
            },
        ),
    ]
