network:
  version: 2
  ethernets:
    eno1:
      dhcp4: no

      addresses:
        - *.*.*.250/24

      routes:
        - to: 0.0.0.0/0
          via: *.*.*.1

      nameservers:
        addresses:
          - *.*.*.*
          - *.*.*.*
          - *.*.*.*
          - *.*.*.*


